### ISSUE TITLE
Allow for automatic Jira ticket creation

### ISSUE THREAD

**Issue by ImDevinC** [echoboomer/incident-bot#395]
Currently, creating a Jira ticket can only be done manually once the incident is created. For our use case, having the JIRA ticket automatically created would be beneficial. I think we can make this a configurable option for users, something like:

```yaml
jira:
  auto_create_incident: True
  auto_create_incident_type: 'Task'
  project: INCMGMT
  issue_types: ['Task', 'Epic', 'Story']
  priorities: ['High', 'Medium', 'Low']
  labels:
    - incident-management
    - etc
```
