### ISSUE TITLE
Allow for updating of Jira ticket status as incident changes status

### ISSUE THREAD

**Issue by ImDevinC** [echoboomer/incident-bot#396]
It would be nice if we could map incident statuses to Jira status optionally, if a ticket exists. Something like the example below. If a `status_mapping` doesn't exist for an incident status, then the Jira ticket wouldn't get an update during that time.

```yaml
jira:
  update_status: True
  status_mapping:
    - incident_status: Investigating
      jira_status: Open
    - incident_status: Identified
      jira_status: In Progress
    - incident_status: Monitoring
      jira_status: In Review
    - incident_status: Resolved
      jira_status: Done
  project: INCMGMT
  issue_types: ['Task', 'Epic', 'Story']
  priorities: ['High', 'Medium', 'Low']
  labels:
    - incident-management
    - etc
```
