### ISSUE TITLE
[BUG] Upgrading severities

### ISSUE THREAD

**Issue by luismartins-td** [echoboomer/incident-bot#418]
**Describe the bug**
I updated the severities on values.yaml and when I open an incident I have the old and the new ones

**Version**
1.8.3

**To Reproduce**
1. Change severities on values.yaml and deploy them

**Environment (please complete the following information):**
 - Platform: Kubernetes

**Comment by luismartins-td** [comment]
From what I saw, the config.yaml keeps the old severities. I already tried to add a new one and I have the same behavior.

**Comment by ImDevinC** [comment]
@luismartins-td can you provide an example of how you set the priorities in your `config.yaml`? I set the following values and it worked as expected:
```yaml
severities:
  priority1: This is a big issue
  priority2: This is a somewhat big issue
  priority3: This is a small issue
  priority4: This may not even be an issue
```
![image](https://github.com/echoboomer/incident-bot/assets/3997333/722bbad5-61b8-44a4-9fdc-67b84d979514)
![image](https://github.com/echoboomer/incident-bot/assets/3997333/e7a3de34-b005-4f5c-95c2-c7e7855c9758)
